#cloud-config

fqdn: ${hostname}

packages:
 - ntp
 - qemu-guest-agent
 
groups:
  - docker

users:
  - name: ubuntu
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: ${ssh_pub_key}
    shell: /bin/bash
    
disk_setup:
  /dev/vda:
    table_type: gpt
    layout: True
    overwrite: True

fs_setup:
  - device: /dev/vda
    filesystem: ext4
    partition: 1

mounts:
  - [ /dev/vda1, ${mount}, auto, "defaults,noexec" ]
  
runcmd:
  - ${rancher_join_command} %{ for role in roles ~} --${role} %{ endfor ~}

ca_certs:
  trusted: 
  - | 
    -----BEGIN CERTIFICATE-----
    MIIF/jCCA+agAwIBAgIIKXE+7me5PfMwDQYJKoZIhvcNAQELBQAwWTEPMA0GA1UE
    AxMGcm91dGVyMQswCQYDVQQGEwJDQTELMAkGA1UECBMCUUMxEDAOBgNVBAcTB05l
    d3BvcnQxDTALBgNVBAoTBGhvbWUxCzAJBgNVBAsTAklUMB4XDTIyMDUxMDIyMTQ1
    M1oXDTMyMDUwNzIyMTQ1M1owWTEPMA0GA1UEAxMGcm91dGVyMQswCQYDVQQGEwJD
    QTELMAkGA1UECBMCUUMxEDAOBgNVBAcTB05ld3BvcnQxDTALBgNVBAoTBGhvbWUx
    CzAJBgNVBAsTAklUMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvyQq
    IJsnns8EHMc8jHYE+pMvbB9XWecmNtmgw7O0VZBC6ezeVoVq5NXSfb+V9KzuS95A
    UHqQn0lnEk4p36xucZkt1zdTgtiFugsJB2vfNJy2qs0IkT5YnqNDORMeaD23lRtL
    +i7yB94hO3ePOHuqPpWWsUaXHu03av2pUkpdwy8RfK3LFIjNFFcwFRB/ok/sixnz
    P1JFk7i65sct7gV9S6Jfp4VTCGkWpbyfjydPYYckTvpAntguf6mNjHXcLaQpWote
    cqwqWHIB1uaOca3TAeq85epXK9eV/9vAn7UO8uLjvnSiChL57QMJoiRvpTQBp76k
    sM9br09wYemdxxCOsCsaSoxX49wTsz0NH7VuwnAopnwuaPWG7N9jOth4zlQskHdf
    OdVUTeRw2RjSXl7srS3KS6s9Ht7f1SkjBGY16XzXxE6fIST9/kW5jNHVCour+3Jg
    Z26NG2PwBlUyPPfac5fcwGgAffsgKLBZIg9yzLw9cf/uDVUIKQ49kqqxJJUW6x0c
    GXuQhHNYTfNGiWGNvp8jYI81KMaF2ordh67pC8Ar3CM5Jzt+alzi3q7gnU1Wt8mv
    8xXTv5Ymw65eO5H9XXOvjXxz2uVHoW4/xGAVPbtUQST0s4ghIbbRGkxZmQwPG86+
    m7VC1gPYibOosLuju9S0Yo6P/4od2Lp721F2yCECAwEAAaOByTCBxjAdBgNVHQ4E
    FgQUSg5U+zWQ3nNErO9iUglyDkVyrQAwgYkGA1UdIwSBgTB/gBRKDlT7NZDec0Ss
    72JSCXIORXKtAKFdpFswWTEPMA0GA1UEAxMGcm91dGVyMQswCQYDVQQGEwJDQTEL
    MAkGA1UECBMCUUMxEDAOBgNVBAcTB05ld3BvcnQxDTALBgNVBAoTBGhvbWUxCzAJ
    BgNVBAsTAklUgggpcT7uZ7k98zAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjAN
    BgkqhkiG9w0BAQsFAAOCAgEAlJHvdpty4OGMt942rrhQPask/sAGi3ifkZ/6gtYn
    Dcq43H6nX2z+5uV0wCsd9p5IyNeZHtJIvH8d7SMQu38BZBvcEZjFKF5A4Pt1GbMh
    EmJ86KEGhg1+bQ73Y8Ev/Xqy6+Tmr98pNLJEdgC/3X02BgWBD41Ubjn2ZRyycaKg
    gIk1HvtCVwIRr7untzYTBpg2YPTOpRcfKmASzpGY1spCu/lp1D5KN2yYNxQy8fpZ
    5/vM+rHloBxeqYxPV8z5EqJlhIp3XKeyWUE6gk3meKkW/3s5a32HVwQ5CqWSiwT3
    kHIikpUA+dQmCvDrnMlnTE0s+c93tI8wvSfy+fhDHTgLp7yqkVcHgqnCiYRBoKgM
    0VH367XjtBHd3Dsy4S6Y9od2cFkJp9yBw7QvqbJU7fsM3sOtw/12geix3fFq0fMh
    VKa8Lw1wcqm0L7TUBWyrOGwNijnoH8pF+b3Lytt/25PqbsPcYeOGf0oygNLyaoU7
    FjO5fuAMwR9KaNPUX6pJaL+b2d/huBJaFE/IN1aUW43edkeGCTYuNKQ5GxhF11Vv
    rFVWRwuxiQmp8VtlNsDZp6baYEMjF6840JhGTNhaPT6uxKCbJnkjHBjCIq9vDavN
    zfwYeqZN0+wE6mFE9Us/wLMEfSDzBkykC5T+5/qAOotC0dI9WldB5hngvjv7mVzh
    sK4=
    -----END CERTIFICATE-----