#cloud-config

packages:
 - ntp
 - qemu-guest-agent
 - open-iscsi
 - nfs-common
 
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_pub_key}
    shell: /bin/bash

disk_setup:
  /dev/vdb:
    table_type: gpt
    layout: True
    overwrite: True

fs_setup:
  - device: /dev/vdb
    filesystem: ext4
    partition: auto

mounts:
  - [ /dev/vdb1, ${mount}, auto, "defaults,noexec" ]
 
runcmd: 
# Temp. for RKE2 on Ubuntu 22.04
  - systemctl stop apparmor.service
  - systemctl disable apparmor.service

%{ if root_ca_cert != "" }
ca_certs:
  trusted: 
  - |
   ${root_ca_cert}
%{ endif }
